site_name: PoshBot Docs
site_description: Documentation for PoshBot, a chat bot written in PowerShell
site_author: Brandon Olin
repo_url: https://github.com/devblackops/PoshBot
edit_uri: edit/master/docs
theme: readthedocs
extra:
    version: 0.1.0